name: flutter_risk_reward_chart
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/radvansky-tomas/flutter_risk_reward_chart

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  community_charts_flutter: ^1.0.4
  equatable: ^2.0.3
